MODULE INIT_VAR_GLOBAL

USE TIMCOM_GENERAL
USE OCN_PARA_GLOBAL
USE CONTROL_GLOBAL
USE ZCO_GLOBAL
USE XYFS_GLOBAL

IMPLICIT NONE

!SAVE

! LEVITUS DATA INFORMATION
INTEGER(2), DIMENSION(33)     ::NZDAT
CHARACTER(128),DIMENSION(4)   ::SEASON

! HELLERMAN WIND FORCE, FULL FILE NAMES TO READ
CHARACTER(128),DIMENSION(12)  ::TXC,TYC

END MODULE INIT_VAR_GLOBAL


!######################################################################

