MODULE CONTROL_GLOBAL
USE TIMCOM_GENERAL
IMPLICIT NONE
! User-defined scalar control parameters
  REAL::DT,DM0_CONST,AV,AVN,NAVG,TAUDT,TAUDTN,DE0_CONST,DMZ0,VBK_CONST 
  INTEGER::DIMEN,KTRM

  REAL::AROUT
  !INTEGER::LOPENN,LOPENS,LOPENE,LOPENW,LTURB,LHEAT,LSOL,LPMOV,LEVP,DIMEN

  REAL::TLX,TLY,TLZ,B,DTLX,DZ0,DX0
  INTEGER::CLIMATO,DX0STD

! original at INIT_VAR_GLOBAL_PRE
  REAL :: TMAX,TL,UINFLOW,VINFLOW
! TEMPORAL
  REAL :: DAODT=192. 

! LATERAL_BOUND_FLAGS 
  INTEGER :: LOPENN=2
  INTEGER :: LOPENS=0
  INTEGER :: LOPENE=1
  INTEGER :: LOPENW=1
  INTEGER :: FL_INFL_N=0
  INTEGER :: FL_INFL_S=0
  INTEGER :: FL_INFL_E=0
  INTEGER :: FL_INFL_W=0
  INTEGER :: FL_SPL_ON=1
  INTEGER :: FL_SWAMP_RE=1

! TSC_FLAGS : TEMPERTURE & SALINITY
  INTEGER :: FL_EOS_OP=5
  INTEGER :: FL_TRACER_ON=0

! SURFACE_BOUND_FLAGS : WIND EFFECT
  INTEGER :: FL_SURF_EP=1
  INTEGER :: FL_EVAP1=0

! PHYSICS
  REAL :: RZMX = 20.
  REAL :: DRAG = .002

! SOLVER
  INTEGER :: MXMASK=18
  REAL :: TOLERANCE=0.01

! PHYSICS_FLAGS
  INTEGER :: FL_TURB_H=1
  INTEGER :: FL_TURB_V=1
  INTEGER :: FL_TURB_V_ADD=0
  INTEGER :: ITF_PHYS=4

! PMOVE_FLAGS
  INTEGER :: FL_PMOVE_ON=0
  INTEGER :: FL_PMOVE_NEWDAY=-30

! NUDGING_FACTOR
  INTEGER :: FL_FNEWFOLD_CALC  =  2
  INTEGER :: FL_NUDGE_HMEAN_T  =  1
  INTEGER :: FL_NUDGE_HMEAN_S  =  1
  INTEGER :: FL_NUDGE_OP_T     =  3
  INTEGER :: FL_NUDGE_OP_S     =  3
  INTEGER :: FL_ARBR_P0        =  0
  REAL    :: NUDGING_HMEAN     = 360.0000
  REAL    :: TAU_CONST         = 360.0000
  REAL    :: TAUN_CONST        = 360.0000
  REAL    :: NUDGE_W           = 360.0000

! FILTERS
  REAL :: FLTW = 0.1
  REAL :: WRAF = 0.53
  INTEGER :: FL_BI_FIL=1

! BATHYMETRY
  INTEGER :: FL_RL_BATHY=1
  INTEGER :: FL_ITPL=1
  INTEGER :: FL_LBS=1

! TSC_FLAGS : TEMPERTURE & SALINITY
  INTEGER :: FL_RL_TS=1

! SURFACE_BOUND_FLAGS : WIND EFFECT
  INTEGER :: FL_WD_ON=1
  INTEGER :: FL_RL_WD=1

! VISCOSITY
  INTEGER :: FL_INI_VIS=0
             != 1: CALCULATE INITIAL VISCOSITY    !
             != 0: NO NEED TO CALCULATE INI. VIS. !
  INTEGER :: FL_BK_VIS=1
             != 1: CALCULATE BACKGROUND VISCOSITY !
             != 0: NO NEED TO CALCULATE BK. VIS.  !

! SOLVER
  INTEGER :: LEVP=1
  INTEGER :: FL_EVP_STP=1

! RIVER_FILE
  CHARACTER(22) :: RIVERFILE='namelist.rivers.empty'


CONTAINS

SUBROUTINE CONTROL_GLOBAL_INITIALIZE
  RUNS = -5
  ISAV = -5
  SCRNOUT = -1
  CPSAV = -5

END SUBROUTINE CONTROL_GLOBAL_INITIALIZE

END MODULE CONTROL_GLOBAL

!#############################################################

MODULE SCA_GLOBAL
! Derived scalars
  REAL::ODT,PRN,DAYS,ORZMX,OFLTW,WATTS
END MODULE SCA_GLOBAL

MODULE DIR_GLOBAL
  CHARACTER(LEN=30) :: IDIR="./INPUT_GLOBAL/", ODIR="./OUTPUT_GLOBAL/", TDIR="./TEMP_GLOBAL/"
END MODULE DIR_GLOBAL
