SUBROUTINE OPEN_OLD_TXT_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=100

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,FILE =FNAME,STATUS="OLD",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_OLD_TXT_FILE


SUBROUTINE OPEN_NEW_TXT_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=200
  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,FILE =FNAME,STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_NEW_TXT_FILE

SUBROUTINE OPEN_BIGENDIAN_OLD_TXT_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=300

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,CONVERT='BIG_ENDIAN',FILE =FNAME,IOSTAT=OPENSTATUS)
  IF (.NOT. ( (OPENSTATUS == 0) .OR. (OPENSTATUS == 202) ) )THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_BIGENDIAN_OLD_TXT_FILE

SUBROUTINE OPEN_BIGENDIAN_NEW_TXT_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=400

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,CONVERT='BIG_ENDIAN',FILE =FNAME,STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (.NOT. ( (OPENSTATUS == 0) .OR. (OPENSTATUS == 202) ) )THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_BIGENDIAN_NEW_TXT_FILE

!**********************************************************************

SUBROUTINE OPEN_BIGENDIAN_OLD_BIN_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=500

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,CONVERT='BIG_ENDIAN',FILE =FNAME,FORM="UNFORMATTED",IOSTAT=OPENSTATUS)
  IF (.NOT. ( (OPENSTATUS == 0) .OR. (OPENSTATUS == 202) ) )THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_BIGENDIAN_OLD_BIN_FILE

!**********************************************************************

SUBROUTINE OPEN_BIGENDIAN_NEW_BIN_FILE(FNAME,FNO)
CHARACTER(LEN=*) :: FNAME
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=600

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  
  OPEN (UNIT=FNO,CONVERT='BIG_ENDIAN',FILE =FNAME,FORM="UNFORMATTED",STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (.NOT. ( (OPENSTATUS == 0) .OR. (OPENSTATUS == 202) ) )THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_BIGENDIAN_NEW_BIN_FILE

SUBROUTINE OPEN_OLD_BIN_FILE(FNAME,BINTYPE,FNO)
CHARACTER(LEN=*) :: FNAME,BINTYPE
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=700

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,CONVERT=BINTYPE,FILE=FNAME,FORM="UNFORMATTED",STATUS="OLD",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_OLD_BIN_FILE

SUBROUTINE OPEN_NEW_BIN_FILE(FNAME,BINTYPE,FNO)
CHARACTER(LEN=*) :: FNAME,BINTYPE
INTEGER :: FNO,OPENSTATUS
LOGICAL :: FOPEN
INTEGER,SAVE :: NUM=800

  DO WHILE(.TRUE.)
    FNO=NUM
    INQUIRE(FNO,OPENED=FOPEN)
    IF ( .NOT. FOPEN ) EXIT
    NUM=NUM+1
  ENDDO
  OPEN (UNIT=FNO,CONVERT=BINTYPE,FILE=FNAME,FORM="UNFORMATTED",STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
  PRINT *, TRIM(FNAME)," not present or wrong filename."
  STOP
  END IF
END SUBROUTINE OPEN_NEW_BIN_FILE
