!
!  PROGRAM USED FOR GENERATING 3-D COORDINATE FOR THE MODEL SIMULATION
!
PROGRAM PREP_UNI
USE CONTROL_GLOBAL
USE GRID_VAR_GLOBAL,ONLY:DE_INI_VAR
USE COUPLING

IMPLICIT NONE

CHARACTER(LEN=16) :: NML_ODIR="./main_nml/"

CALL CONTROL_GLOBAL_INITIALIZE

CALL METGEN
WRITE(*,*), 'metgen done'

CALL INDATA
WRITE(*,*), 'indata done'

CALL PREP_TIMCOM
PRINT *, 'PREP_TIMCOM done'

CALL CASE_INFO_ASCII_OUTPUT

CALL CASE_INFO_BINARY_OUTPUT

CALL RUN_NML_OUTPUT

CALL MAIN_NML_OUTPUT

CALL DE_INI_VAR

CALL DE_INI_VAR_COUPLE

CALL COPY_NAMELIST("GLOBAL",TRIM(NML_ODIR),TRIM(WORKDIR))

CONTAINS

SUBROUTINE CASE_INFO_ASCII_OUTPUT
USE OCN_PARA
  CHARACTER(LEN=256) :: FNAME
  INTEGER :: FNO
  FNAME=TRIM(NML_ODIR)//'/case_info'
  CALL OPEN_NEW_TXT_FILE(TRIM(FNAME),FNO)
  WRITE(FNO,"(A)")"Notice: This file describe the information of the case, edit this file will not change any thing!"
  WRITE(FNO,NML=CASE_INFO)
  WRITE(FNO,NML=GLOBAL)
  CLOSE(FNO) 
END SUBROUTINE CASE_INFO_ASCII_OUTPUT

SUBROUTINE CASE_INFO_BINARY_OUTPUT
USE OCN_PARA
  CHARACTER(LEN=256) :: FNAME
  INTEGER :: FNO

  FNAME=TRIM(NML_ODIR)//'/.case_info'
  CALL OPEN_BIGENDIAN_NEW_BIN_FILE(TRIM(FNAME),FNO)
  WRITE(FNO)CASE_NAME
  WRITE(FNO)DSCRIB
  CLOSE(FNO)

  FNAME=TRIM(WORKDIR)//'/INPUT_GLOBAL/GLOBAL'
  CALL OPEN_BIGENDIAN_NEW_BIN_FILE(TRIM(FNAME),FNO)
  WRITE(FNO)I0_GLOBAL,J0_GLOBAL,K0_GLOBAL

! LATERAL_BOUND_FLAGS
  WRITE(FNO) LOPENN,LOPENS,LOPENE,LOPENW,FL_INFL_N,FL_INFL_S,FL_INFL_E,FL_INFL_W
! TSC_FLAGS except FL_TRACER_ON
  WRITE(FNO) FL_RL_TS,TMAX,FL_EOS_OP
! WIND_FLAGS
  WRITE(FNO) FL_WD_ON,FL_RL_WD

  CLOSE(FNO)
END SUBROUTINE CASE_INFO_BINARY_OUTPUT


SUBROUTINE RUN_NML_OUTPUT
  INTEGER :: OPENSTATUS
  CHARACTER(LEN=256) :: FNAME

! namelist.run output for general namelist in timcom main process
  FNAME=TRIM(NML_ODIR)//'/namelist000.run'  
  OPEN(UNIT=999,FILE=TRIM(FNAME),FORM='FORMATTED',DELIM='APOSTROPHE',STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
    PRINT *, "namelist file not present or wrong filename."
    STOP
  END IF
!  WRITE(999,"(A)")" "
!  WRITE(999,NML=CASE_INFO)
  WRITE(999,"(A)")" "
  WRITE(999,NML=WORK_DIR)
  WRITE(999,"(A)")" "
!  WRITE(999,NML=GLOBAL)
!  WRITE(999,"(A)")" "
  WRITE(999,NML=RUN_STEPS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=ATMO_FORCING)
  WRITE(999,"(A)")" "
  WRITE(999,NML=SNAPSHOT_OUTPUT_STEPS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=VAR_I0J0K1_OUTPUT_SIGNALS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=VAR_I0J0K0_OUTPUT_SIGNALS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=VAR_I0J0_OUTPUT_SIGNALS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=SCREEN_OUTPUT_STEPS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=CHECKPOINT_STEPS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=TIME0)
  WRITE(999,"(A)")" "

  CLOSE(999)

END SUBROUTINE RUN_NML_OUTPUT


SUBROUTINE MAIN_NML_OUTPUT
! output namelist to be used for new main calculation
USE MAIN_NAMELIST_GLOBAL

  INTEGER :: OPENSTATUS
  CHARACTER(LEN=256) :: FNAME

! namelist000.input_GLOBAL output for GLOBAL namelist in timcom main process
  FNAME=TRIM(NML_ODIR)//'/namelist000.inp_GLOBAL' 
  OPEN(UNIT=999,FILE=TRIM(FNAME),FORM='FORMATTED',DELIM='APOSTROPHE',STATUS="REPLACE",IOSTAT=OPENSTATUS)
  IF (OPENSTATUS > 0) THEN
    PRINT *, "namelist file not present or wrong filename."
    STOP
  END IF
  WRITE(999,"(A)")" "
  WRITE(999,NML=GRID_XY)
  WRITE(999,"(A)")" "
  WRITE(999,NML=TEMPORAL)
  WRITE(999,"(A)")" "
  WRITE(999,NML=PHYSICS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=SOLVER)
  WRITE(999,"(A)")" "
  WRITE(999,NML=INFLOW_BOUND_COND)
  WRITE(999,"(A)")" "
  WRITE(999,NML=PHYSICS_FLAGS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=TSC_FLAGS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=EP_FLAGS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=NUDGING_FACTOR)
  WRITE(999,"(A)")" "
  WRITE(999,NML=SPONGE_AND_SWAMP_LAYERS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=FILTERS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=VISCOSITY_FLAGS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=PMOVE_FLAGS)
  WRITE(999,"(A)")" "
  WRITE(999,NML=RIVER_FILE)
  WRITE(999,"(A)")" "
  CLOSE(999)

END SUBROUTINE MAIN_NML_OUTPUT

END PROGRAM PREP_UNI

