MODULE TPS_NAMELIST_GLOBAL
USE INIT_VAR_GLOBAL
IMPLICIT NONE

! namelist variables in namelist.tps_GLOBAL

  NAMELIST /DIMENSIONS/ DIMEN,TLX,TLY,TLZ 
  NAMELIST /GRID_XY/ COORD_SYS,X0DEG,Y0DEG,DXMNUT,DXDEG,DYDEG,DYDX,DX0STD
  NAMELIST /TEMPORAL/ DAODT
  NAMELIST /PHYSICS/ DM0_CONST,DE0_CONST,DMZ0,TL,RZMX,DRAG,VBK_CONST
  NAMELIST /SOLVER/ N0,NBIR,LEVP
  NAMELIST /Z_OPTION/ ZOP,ZTOP
  NAMELIST /Z_LINEAR/ C,D
  NAMELIST /LATERAL_BOUND_FLAGS/ LOPENW,LOPENE,LOPENS,LOPENN,FL_INFL_W,FL_INFL_E,FL_INFL_S,FL_INFL_N
  NAMELIST /INFLOW_BOUND_COND/ UINFLOW,VINFLOW 
  NAMELIST /BATHY_FLAGS/ FL_RL_BATHY, FL_ITPL, FL_LBS
  NAMELIST /TSC_FLAGS/ FL_RL_TS,TMAX,FL_EOS_OP
  NAMELIST /WIND_FLAGS/ FL_WD_ON, FL_RL_WD

INTEGER,PRIVATE :: FNO_TPS

CONTAINS

SUBROUTINE OPEN_TPS_NAMELIST_FILE(FNO)
INTEGER :: FNO
  CALL OPEN_OLD_TXT_FILE("namelist.tps_GLOBAL",FNO)
  FNO_TPS=FNO
END SUBROUTINE OPEN_TPS_NAMELIST_FILE

SUBROUTINE CLOSE_TPS_NAMELIST_FILE
  CLOSE(FNO_TPS)
END SUBROUTINE CLOSE_TPS_NAMELIST_FILE

END MODULE TPS_NAMELIST_GLOBAL

!######################################################################

MODULE MAIN_NAMELIST_GLOBAL
USE INIT_VAR_GLOBAL
USE OCN_PARA_GLOBAL
IMPLICIT NONE

! namelist variables in namelist.simulate_GLOBAL

  NAMELIST /GRID_XY/ COORD_SYS,X0DEG,Y0DEG,DXMNUT,DXDEG,DYDEG,DYDX,DX0STD
  NAMELIST /TEMPORAL/ DAODT
  NAMELIST /PHYSICS/ DM0_CONST,DE0_CONST,DMZ0,TL,RZMX,DRAG,VBK_CONST
  NAMELIST /SOLVER/ N0,NBIR,MXMASK,TOLERANCE,FL_EVP_STP
  NAMELIST /INFLOW_BOUND_COND/ UINFLOW,VINFLOW 
  NAMELIST /PHYSICS_FLAGS/ FL_TURB_H,FL_TURB_V,FL_TURB_V_ADD,ITF_PHYS
  NAMELIST /TSC_FLAGS/FL_TRACER_ON
  NAMELIST /EP_FLAGS/FL_SURF_EP,FL_EVAP1
  NAMELIST /NUDGING_FACTOR/ FL_FNEWFOLD_CALC,FL_NUDGE_HMEAN_T,FL_NUDGE_HMEAN_S,&
    FL_NUDGE_OP_T,FL_NUDGE_OP_S,FL_ARBR_P0,NUDGING_HMEAN,&
    TAU_CONST,TAUN_CONST,NUDGE_W
  NAMELIST /SPONGE_AND_SWAMP_LAYERS/ FL_SPL_ON,FL_SWAMP_RE
  NAMELIST /FILTERS/ FLTW,WRAF,FL_BI_FIL
  NAMELIST /VISCOSITY_FLAGS/ FL_INI_VIS, FL_BK_VIS
  NAMELIST /PMOVE_FLAGS/FL_PMOVE_ON,FL_PMOVE_NEWDAY
  NAMELIST /RIVER_FILE/RIVERFILE

END MODULE MAIN_NAMELIST_GLOBAL


